services:
  web:
    build: web
    ports:
      - "${NEXT_PUBLIC_WEB_PORT}:${NEXT_PUBLIC_WEB_PORT}"
    environment:
      - PORT=${NEXT_PUBLIC_WEB_PORT}
    env_file:
      - ./.env
      - ./config/web.env
    # Docker compose's watcher so application automatically updates
    develop:
      watch:
        - action: sync
          path: ./web/src
          target: /app/src
        - action: sync
          path: ./web/public
          target: /app/public
        
        # rebuild when packages changes/dockerfile updated
        - action: rebuild
          path: ./web/package.json
        - action: rebuild
          path: ./web/Dockerfile
  api:
    build: backend
    ports:
      - "${NEXT_PUBLIC_API_PORT}:${NEXT_PUBLIC_API_PORT}"
    environment:
      - PORT=${NEXT_PUBLIC_API_PORT}
    env_file:
      - ./.env
      - ./config/database.env
      - ./config/backend.env
    networks:
      - default
      - backend_net
    depends_on:
      database:
        condition: service_healthy
        required: false
    # Docker compose's watcher so application automatically updates
    develop:
      watch:
        # rebuild when code changes/dockerfile updated
        - action: rebuild
          path: ./backend
        - action: rebuild
          path: ./backend/Dockerfile
  # Database optionally can be started if not
  # having external instance
  database:
    build: database
    ports:
      - 5432:5432
    env_file:
      - ./config/database.env
    profiles:
      - internalDatabase
    networks:
      - backend_net
      - default
    # Check till mysql is ready, so API server does not start till database ready
    healthcheck:
      test: pg_isready -h 127.0.0.1 -p $$DATABASE_PORT -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    develop:
      watch:
        # rebuild when code dockerfile/seeds updated
        - action: rebuild
          path: ./database

networks:
  backend_net:
    internal: true

